<?php
declare(strict_types=1);

const ROOT_DIR = __DIR__ . '/..';
const DATABASE_PATH = ROOT_DIR . '/data/cwdge.db';
const UPLOAD_DIRECTORY = __DIR__ . '/uploads';

if (!is_dir(dirname(DATABASE_PATH))) {
    mkdir(dirname(DATABASE_PATH), 0775, true);
}
if (!is_dir(UPLOAD_DIRECTORY)) {
    mkdir(UPLOAD_DIRECTORY, 0775, true);
}

$db = new PDO('sqlite:' . DATABASE_PATH, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$db->exec('PRAGMA journal_mode = WAL');
$db->exec("CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, phone TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cards (id INTEGER PRIMARY KEY AUTOINCREMENT, company_name TEXT NOT NULL, customer_id INTEGER NOT NULL, plan TEXT NOT NULL DEFAULT 'Trial', card_status TEXT NOT NULL DEFAULT 'Active', payment_status TEXT NOT NULL DEFAULT 'Pending', amount INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id INTEGER NOT NULL, amount INTEGER NOT NULL, payment_method TEXT NOT NULL, payment_status TEXT NOT NULL DEFAULT 'Paid', paid_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(card_id) REFERENCES cards(id));
CREATE TABLE IF NOT EXISTS enquiries (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id INTEGER NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, message TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(card_id) REFERENCES cards(id));
CREATE TABLE IF NOT EXISTS admin_settings (id INTEGER PRIMARY KEY CHECK (id = 1), display_name TEXT NOT NULL DEFAULT 'Asorkar', email_notifications TEXT NOT NULL DEFAULT 'Payment and card status updates', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contact_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, phone TEXT NOT NULL, email TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);");

function columns(PDO $db, string $table): array { return array_column($db->query("PRAGMA table_info($table)")->fetchAll(PDO::FETCH_ASSOC), 'name'); }
function addColumn(PDO $db, string $table, string $column, string $definition): void { if (!in_array($column, columns($db, $table), true)) $db->exec("ALTER TABLE $table ADD COLUMN $column $definition"); }
addColumn($db, 'customers', 'password', 'TEXT');
addColumn($db, 'cards', 'tagline', 'TEXT');
foreach (['selected_theme' => "TEXT NOT NULL DEFAULT 'Ocean'", 'logo_url' => 'TEXT', 'first_name' => 'TEXT', 'last_name' => 'TEXT', 'designation' => 'TEXT', 'alternate_phone' => 'TEXT', 'whatsapp' => 'TEXT', 'address' => 'TEXT', 'website' => 'TEXT', 'location' => 'TEXT', 'established_on' => 'TEXT', 'about_us' => 'TEXT', 'facebook_url' => 'TEXT', 'twitter_url' => 'TEXT', 'instagram_url' => 'TEXT', 'linkedin_url' => 'TEXT', 'youtube_url' => 'TEXT', 'pinterest_url' => 'TEXT', 'video_1_url' => 'TEXT', 'video_2_url' => 'TEXT', 'video_3_url' => 'TEXT', 'video_4_url' => 'TEXT', 'video_5_url' => 'TEXT', 'paytm_number' => 'TEXT', 'google_pay_number' => 'TEXT', 'phonepe_number' => 'TEXT', 'bank_name' => 'TEXT', 'account_holder' => 'TEXT', 'bank_account_number' => 'TEXT', 'ifsc_code' => 'TEXT', 'account_type' => 'TEXT', 'paytm_qr_url' => 'TEXT', 'google_pay_qr_url' => 'TEXT', 'phonepe_qr_url' => 'TEXT', 'products_json' => 'TEXT', 'ecommerce_json' => 'TEXT', 'gallery_json' => 'TEXT'] as $column => $definition) addColumn($db, 'cards', $column, $definition);
$db->exec('INSERT OR IGNORE INTO admin_settings (id) VALUES (1)');
if ((int) $db->query('SELECT COUNT(*) FROM customers')->fetchColumn() === 0) {
    $db->beginTransaction();
    $customer = $db->prepare('INSERT INTO customers (name, email, phone) VALUES (?, ?, ?)');
    foreach ([['Asorkars Soap', 'hello@asorkarssoap.in', '+91 98765 10314'], ['Rhea Mehta', 'rhea@studioelevate.in', '+91 98111 42018'], ['Arjun Kapoor', 'arjun@northstarworks.in', '+91 98207 66109']] as $row) $customer->execute($row);
    $card = $db->prepare('INSERT INTO cards (company_name, customer_id, plan, card_status, payment_status, amount, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)');
    $card->execute(['Asorkars Soap', 1, 'Trial', 'Active', 'Pending', 999, '2026-08-18T10:00:00.000Z']); $card->execute(['Studio Elevate', 2, 'Professional', 'Active', 'Paid', 2499, '2026-08-02T10:00:00.000Z']); $card->execute(['Northstar Works', 3, 'Professional', 'Paused', 'Paid', 2499, '2026-07-24T10:00:00.000Z']);
    $payment = $db->prepare('INSERT INTO payments (card_id, amount, payment_method, paid_at) VALUES (?, ?, ?, ?)'); $payment->execute([2, 2499, 'UPI', '2026-08-02T10:00:00.000Z']); $payment->execute([3, 2499, 'Card', '2026-07-24T10:00:00.000Z']);
    $db->commit();
}

function json(mixed $body, int $status = 200): never { http_response_code($status); header('Content-Type: application/json'); echo json_encode($body, JSON_UNESCAPED_SLASHES); exit; }
function input(): array { $data = json_decode(file_get_contents('php://input'), true); return is_array($data) ? $data : []; }
function one(PDO $db, string $sql, array $params = []): ?array { $statement = $db->prepare($sql); $statement->execute($params); $row = $statement->fetch(PDO::FETCH_ASSOC); return $row ?: null; }
function all(PDO $db, string $sql, array $params = []): array { $statement = $db->prepare($sql); $statement->execute($params); return $statement->fetchAll(PDO::FETCH_ASSOC); }
function execute(PDO $db, string $sql, array $params = []): PDOStatement { $statement = $db->prepare($sql); $statement->execute($params); return $statement; }
function value(array $data, string $key): mixed { return $data[$key] ?? null; }
function cardExists(PDO $db, string $id): bool { return one($db, 'SELECT id FROM cards WHERE id = ?', [$id]) !== null; }
function cardSlug(string $companyName): string { $slug = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $companyName) ?: $companyName; $slug = strtolower(trim((string)preg_replace('/[^a-zA-Z0-9]+/', '-', $slug), '-')); $slug = $slug === '' ? 'card' : $slug; return ctype_digit($slug) ? "company-$slug" : $slug; }
function cardPath(PDO $db, array $card): string { $cards = all($db, 'SELECT id, company_name FROM cards'); $slugs = array_map(fn($item) => cardSlug((string)$item['company_name']), $cards); $slug = cardSlug((string)$card['company_name']); $candidate = count(array_keys($slugs, $slug, true)) > 1 ? "$slug-{$card['id']}" : $slug; $candidates = array_map(fn($item, $itemSlug) => count(array_keys($slugs, $itemSlug, true)) > 1 ? "$itemSlug-{$item['id']}" : $itemSlug, $cards, $slugs); return '/cards/' . (count(array_keys($candidates, $candidate, true)) > 1 ? "$candidate-{$card['id']}" : $candidate); }
function publicCard(PDO $db, string $reference): ?array { if (ctype_digit($reference)) return one($db, "SELECT cards.* FROM cards WHERE cards.id = ? AND cards.card_status = 'Active'", [$reference]); foreach (all($db, "SELECT cards.* FROM cards WHERE cards.card_status = 'Active'") as $card) if (cardPath($db, $card) === '/cards/' . $reference) return $card; return null; }
function saveUploads(string $prefix): array { $saved = []; foreach ($_FILES as $field => $file) { $names = is_array($file['name']) ? $file['name'] : [$file['name']]; $temps = is_array($file['tmp_name']) ? $file['tmp_name'] : [$file['tmp_name']]; $sizes = is_array($file['size']) ? $file['size'] : [$file['size']]; foreach ($names as $i => $name) { if (!$name || ($sizes[$i] ?? 0) > 250 * 1024 || !is_uploaded_file($temps[$i])) continue; $clean = preg_replace('/[^a-zA-Z0-9._-]/', '-', basename($name)); $filename = round(microtime(true) * 1000) . '-' . $prefix . '-' . $clean; if (move_uploaded_file($temps[$i], UPLOAD_DIRECTORY . '/' . $filename)) $saved[] = [$field, '/uploads/' . $filename]; } } return $saved; }
function saveQrUploads(): array { $columns = ['paytmQrImage' => 'paytm_qr_url', 'googlePayQrImage' => 'google_pay_qr_url', 'phonepeQrImage' => 'phonepe_qr_url']; $saved = []; foreach ($columns as $field => $column) { $file = $_FILES[$field] ?? null; if (!$file || $file['error'] === UPLOAD_ERR_NO_FILE) continue; if ($file['error'] !== UPLOAD_ERR_OK) json(['error' => 'Unable to upload the QR image. Please try again.'], 400); if ($file['size'] > 250 * 1024) json(['error' => 'Each QR image must be 250 KB or smaller.'], 400); $image = is_uploaded_file($file['tmp_name']) ? @getimagesize($file['tmp_name']) : false; if (!$image) json(['error' => 'Upload a valid image file for each QR code.'], 400); $extension = image_type_to_extension($image[2], false); if (!in_array($extension, ['gif', 'jpeg', 'png', 'webp'], true)) json(['error' => 'QR images must be GIF, JPEG, PNG, or WebP files.'], 400); $filename = round(microtime(true) * 1000) . '-qr-' . $field . '.' . $extension; if (!move_uploaded_file($file['tmp_name'], UPLOAD_DIRECTORY . '/' . $filename)) json(['error' => 'Unable to save the QR image. Please try again.'], 500); $saved[$column] = '/uploads/' . $filename; } return $saved; }

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$cardQuery = 'SELECT cards.*, customers.name AS customer_name, customers.email AS customer_email, customers.phone AS customer_phone FROM cards JOIN customers ON customers.id = cards.customer_id';
if (preg_match('#^/api/customer/cards/(\d+)/details$#', $path, $match) && $method === 'PATCH') { $data = input(); $columns = ['company_name','logo_url','tagline','first_name','last_name','designation','alternate_phone','whatsapp','address','website','location','established_on','about_us']; $keys = ['companyName','logoUrl','tagline','firstName','lastName','designation','alternatePhone','whatsapp','address','website','location','establishedOn','aboutUs']; $values = array_map(fn($key) => value($data, $key) ?: null, $keys); execute($db, 'UPDATE cards SET ' . implode(', ', array_map(fn($column) => "$column = ?", $columns)) . ' WHERE id = ?', [...$values, $match[1]]); json(one($db, "$cardQuery WHERE cards.id = ?", [$match[1]])); }
if ($path === '/health') { header('Content-Type: text/plain'); echo "ok\n"; exit; }
if ($path === '/api/login' && $method === 'POST') { $data = input(); if (value($data, 'email') === 'admin@admin.com' && value($data, 'password') === '123456789') json(['name' => 'Asorkar', 'role' => 'Administrator']); json(['error' => 'Use the local demonstration credentials to sign in.'], 401); }
if ($path === '/api/contact' && $method === 'POST') { $data = input(); $name = trim((string)value($data, 'name')); $phone = trim((string)value($data, 'phone')); $email = trim((string)value($data, 'email')); $message = trim((string)value($data, 'message')); if ($name === '' || $phone === '' || $email === '' || $message === '') json(['error' => 'Please complete every field.'], 400); if (strlen($name) > 120 || strlen($phone) > 40 || strlen($email) > 254 || strlen($message) > 2000) json(['error' => 'Please shorten your message and try again.'], 400); if (!filter_var($email, FILTER_VALIDATE_EMAIL)) json(['error' => 'Enter a valid email address.'], 400); execute($db, 'INSERT INTO contact_messages (name, phone, email, message) VALUES (?, ?, ?, ?)', [$name, $phone, $email, $message]); json(['success' => true], 201); }
if ($path === '/api/customer/register' && $method === 'POST') { $data = input(); if (one($db, 'SELECT id FROM customers WHERE email = ?', [value($data, 'email')])) json(['error' => 'An account already exists for this email.'], 409); $db->beginTransaction(); execute($db, 'INSERT INTO customers (name, email, phone, password) VALUES (?, ?, ?, ?)', [value($data, 'name'), value($data, 'email'), value($data, 'phone'), value($data, 'password')]); $customerId = $db->lastInsertId(); execute($db, "INSERT INTO cards (company_name, customer_id, plan, card_status, payment_status, amount) VALUES (?, ?, 'Trial', 'Active', 'Pending', 999)", [value($data, 'companyName'), $customerId]); $cardId = $db->lastInsertId(); $db->commit(); json(['name' => value($data, 'name'), 'email' => value($data, 'email'), 'cardId' => (int)$cardId], 201); }
if ($path === '/api/customer/login' && $method === 'POST') { $data = input(); $customer = one($db, 'SELECT id, name, email FROM customers WHERE email = ? AND password = ?', [value($data, 'email'), value($data, 'password')]); $customer ? json($customer) : json(['error' => 'Incorrect customer email or password.'], 401); }
if ($path === '/api/customer/cards' && $method === 'GET') { $customer = one($db, 'SELECT id FROM customers WHERE email = ?', [$_GET['email'] ?? '']); $customer ? json(all($db, 'SELECT cards.*, customers.name AS customer_name, customers.email AS customer_email, customers.phone FROM cards JOIN customers ON customers.id = cards.customer_id WHERE cards.customer_id = ? ORDER BY cards.id DESC', [$customer['id']])) : json(['error' => 'Customer account not found.'], 404); }
if (preg_match('#^/api/public/cards/([^/]+)$#', $path, $match) && $method === 'GET') { $card = publicCard($db, rawurldecode($match[1])); $card ? json(one($db, "$cardQuery WHERE cards.id = ?", [$card['id']])) : json(['error' => 'Public card not found.'], 404); }
if (preg_match('#^/api/customer/cards/(\d+)/public-link$#', $path, $match) && $method === 'GET') { $card = one($db, 'SELECT id, company_name FROM cards WHERE id = ?', [$match[1]]); $card ? json(['path' => cardPath($db, $card)]) : json(['error' => 'Card not found.'], 404); }
if ($path === '/api/summary' && $method === 'GET') json(['cards' => (int)$db->query('SELECT COUNT(*) FROM cards')->fetchColumn(), 'customers' => (int)$db->query('SELECT COUNT(*) FROM customers')->fetchColumn(), 'active' => (int)$db->query("SELECT COUNT(*) FROM cards WHERE card_status = 'Active'")->fetchColumn(), 'pending' => (int)$db->query("SELECT COUNT(*) FROM cards WHERE payment_status != 'Paid'")->fetchColumn()]);
if ($path === '/api/cards' && $method === 'GET') json(all($db, "$cardQuery ORDER BY cards.id DESC"));
if ($path === '/api/cards/export.csv' && $method === 'GET') { $columns = ['Card ID', 'Company Name', 'Customer Name', 'Customer Email', 'Customer Phone', 'Plan', 'Theme', 'Card Status', 'Payment Status', 'Amount (INR)', 'Created At']; header('Content-Type: text/csv'); header('Content-Disposition: attachment; filename="cwdge-managed-cards.csv"'); $out = fopen('php://output', 'w'); fputcsv($out, $columns); foreach (all($db, "$cardQuery ORDER BY cards.id DESC") as $card) fputcsv($out, [$card['id'], $card['company_name'], $card['customer_name'], $card['customer_email'], $card['customer_phone'], $card['plan'], $card['selected_theme'], $card['card_status'], $card['payment_status'], $card['amount'], $card['created_at']]); exit; }
if ($path === '/api/customers' && $method === 'GET') json(all($db, 'SELECT * FROM customers ORDER BY id DESC'));
if ($path === '/api/payments' && $method === 'GET') json(all($db, 'SELECT payments.*, cards.company_name FROM payments JOIN cards ON cards.id = payments.card_id ORDER BY paid_at DESC'));
if ($path === '/api/admin/settings' && $method === 'GET') json(one($db, 'SELECT display_name, email_notifications FROM admin_settings WHERE id = 1'));
if ($path === '/api/admin/settings' && $method === 'PATCH') { $data = input(); execute($db, "UPDATE admin_settings SET display_name = ?, email_notifications = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1", [value($data, 'displayName') ?: 'Asorkar', value($data, 'emailNotifications') ?: 'Payment and card status updates']); json(one($db, 'SELECT display_name, email_notifications FROM admin_settings WHERE id = 1')); }
if ($path === '/api/search' && $method === 'GET') { $term = trim((string)($_GET['q'] ?? '')); json($term === '' ? [] : all($db, "$cardQuery WHERE cards.company_name LIKE ? OR customers.name LIKE ? OR customers.email LIKE ? ORDER BY cards.id DESC", array_fill(0, 3, "%$term%"))); }
if ($path === '/api/cards' && $method === 'POST') { $data = input(); $customer = one($db, 'SELECT id FROM customers WHERE email = ?', [value($data, 'email')]); if (!$customer) { execute($db, 'INSERT INTO customers (name, email, phone) VALUES (?, ?, ?)', [value($data, 'customerName'), value($data, 'email'), value($data, 'phone')]); $customer = ['id' => $db->lastInsertId()]; } $plan = value($data, 'plan') ?: 'Trial'; $amount = $plan === 'Professional' ? 2499 : ($plan === 'Business' ? 4999 : 999); execute($db, "INSERT INTO cards (company_name, customer_id, plan, card_status, payment_status, amount) VALUES (?, ?, ?, 'Active', 'Pending', ?)", [value($data, 'companyName'), $customer['id'], $plan, $amount]); json(one($db, "$cardQuery WHERE cards.id = ?", [$db->lastInsertId()]), 201); }
if (preg_match('#^/api/cards/(\d+)$#', $path, $match) && $method === 'PATCH') { $data = input(); execute($db, 'UPDATE cards SET card_status = COALESCE(?, card_status), payment_status = COALESCE(?, payment_status) WHERE id = ?', [value($data, 'cardStatus'), value($data, 'paymentStatus'), $match[1]]); json(one($db, "$cardQuery WHERE cards.id = ?", [$match[1]])); }
if (preg_match('#^/api/cards/(\d+)/pay$#', $path, $match) && $method === 'POST') { $card = one($db, 'SELECT * FROM cards WHERE id = ?', [$match[1]]); if (!$card) json(['error' => 'Card not found.'], 404); $db->beginTransaction(); execute($db, 'INSERT INTO payments (card_id, amount, payment_method) VALUES (?, ?, ?)', [$card['id'], $card['amount'], 'Manual payment']); execute($db, "UPDATE cards SET payment_status = 'Paid' WHERE id = ?", [$card['id']]); $db->commit(); json(['success' => true]); }
if (preg_match('#^/api/cards/(\d+)/enquiries$#', $path, $match)) { if ($method === 'GET') json(all($db, 'SELECT * FROM enquiries WHERE card_id = ? ORDER BY created_at DESC, id DESC', [$match[1]])); if ($method === 'POST') { $data = input(); if (!value($data, 'name') || !value($data, 'email') || !value($data, 'message')) json(['error' => 'Name, email, and message are required.'], 400); if (!cardExists($db, $match[1])) json(['error' => 'Card not found.'], 404); execute($db, 'INSERT INTO enquiries (card_id, name, email, phone, message) VALUES (?, ?, ?, ?, ?)', [$match[1], value($data, 'name'), value($data, 'email'), value($data, 'phone'), value($data, 'message')]); json(['id' => (int)$db->lastInsertId()], 201); } }
if (preg_match('#^/api/customer/cards/(\d+)/payment-options$#', $path, $match) && $method === 'PATCH') { $data = input(); $columns = ['paytm_number','google_pay_number','phonepe_number','bank_name','account_holder','bank_account_number','ifsc_code','account_type']; $keys = ['paytmNumber','googlePayNumber','phonepeNumber','bankName','accountHolder','bankAccountNumber','ifscCode','accountType']; $values = array_map(fn($key) => value($data, $key) ?: null, $keys); execute($db, 'UPDATE cards SET ' . implode(', ', array_map(fn($column) => "$column = ?", $columns)) . ' WHERE id = ?', [...$values, $match[1]]); json(one($db, "$cardQuery WHERE cards.id = ?", [$match[1]])); }
if (preg_match('#^/api/customer/cards/(\d+)/(theme|details|social-links|payment-options|products|ecommerce)$#', $path, $match) && $method === 'PATCH') { $id = $match[1]; $route = $match[2]; $data = input(); if ($route === 'theme') { $theme = value($data, 'theme'); if (!in_array($theme, ['Ocean', 'Forest', 'Berry', 'Monochrome'], true)) json(['error' => 'Select a valid card theme.'], 400); execute($db, 'UPDATE cards SET selected_theme = ? WHERE id = ?', [$theme, $id]); json(['success' => true, 'theme' => $theme]); } $maps = ['details' => [['company_name','logo_url','first_name','last_name','designation','alternate_phone','whatsapp','address','website','location','established_on','about_us'], ['companyName','logoUrl','firstName','lastName','designation','alternatePhone','whatsapp','address','website','location','establishedOn','aboutUs']], 'social-links' => [['facebook_url','twitter_url','instagram_url','linkedin_url','youtube_url','pinterest_url','video_1_url','video_2_url','video_3_url','video_4_url','video_5_url'], ['facebookUrl','twitterUrl','instagramUrl','linkedinUrl','youtubeUrl','pinterestUrl','video1Url','video2Url','video3Url','video4Url','video5Url']], 'payment-options' => [['paytm_number','google_pay_number','phonepe_number','bank_name','account_holder','bank_account_number','ifsc_code','account_type','paytm_qr_url','google_pay_qr_url','phonepe_qr_url'], ['paytmNumber','googlePayNumber','phonepeNumber','bankName','accountHolder','bankAccountNumber','ifscCode','accountType','paytmQrUrl','googlePayQrUrl','phonepeQrUrl']]]; if ($route === 'products' || $route === 'ecommerce') { $products = is_array($data['products'] ?? null) ? array_slice($data['products'], 0, $route === 'products' ? 10 : 20) : []; execute($db, 'UPDATE cards SET ' . ($route === 'products' ? 'products_json' : 'ecommerce_json') . ' = ? WHERE id = ?', [json_encode($products), $id]); json(['success' => true, 'products' => $products]); } [$columns, $keys] = $maps[$route]; $values = array_map(fn($key) => value($data, $key) ?: null, $keys); $sql = 'UPDATE cards SET ' . implode(', ', array_map(fn($column) => "$column = ?", $columns)) . ' WHERE id = ?'; execute($db, $sql, [...$values, $id]); if ($route === 'details') { execute($db, 'UPDATE customers SET phone = ? WHERE id = (SELECT customer_id FROM cards WHERE id = ?)', [value($data, 'phone'), $id]); json(one($db, 'SELECT * FROM cards WHERE id = ?', [$id])); } json(['success' => true]); }
if (preg_match('#^/api/customer/cards/(\d+)/(products/attachments|ecommerce/attachments|gallery)$#', $path, $match) && $method === 'POST') { $id = $match[1]; $route = $match[2]; if (!cardExists($db, $id)) json(['error' => 'Card not found.'], 404); $uploads = saveUploads($route === 'gallery' ? 'gallery' : 'attachment'); if ($route === 'gallery') { $images = array_column($uploads, 1); execute($db, 'UPDATE cards SET gallery_json = ? WHERE id = ?', [json_encode($images), $id]); json(['success' => true, 'images' => $images]); } $column = str_starts_with($route, 'products') ? 'products_json' : 'ecommerce_json'; $products = json_decode((string)(one($db, "SELECT $column FROM cards WHERE id = ?", [$id])[$column] ?? '[]'), true) ?: []; foreach ($uploads as [$field, $url]) { $index = (int)preg_replace('/\D+/', '', $field); if (isset($products[$index])) $products[$index]['image'] = $url; } execute($db, "UPDATE cards SET $column = ? WHERE id = ?", [json_encode($products), $id]); json(['success' => true, 'products' => $products]); }

if (preg_match('#^/api/customer/cards/(\d+)/payment-options/qr$#', $path, $match) && $method === 'POST') { $id = $match[1]; if (!cardExists($db, $id)) json(['error' => 'Card not found.'], 404); $uploads = saveQrUploads(); if (!$uploads) json(['error' => 'Choose at least one QR image to upload.'], 400); $columns = array_keys($uploads); execute($db, 'UPDATE cards SET ' . implode(' = ?, ', $columns) . ' = ? WHERE id = ?', [...array_values($uploads), $id]); json(one($db, "$cardQuery WHERE cards.id = ?", [$id])); }

if ($path === '/') {
    header('Content-Type: text/html; charset=UTF-8');
    readfile(__DIR__ . '/landing.html');
    exit;
}

if (!str_starts_with($path, '/api/')) {
    header('Content-Type: text/html; charset=UTF-8');
    readfile(__DIR__ . '/index.html');
    exit;
}

http_response_code(404);
header('Content-Type: text/plain');
echo "Not found\n";
